version: '3.8'

services:
  web-sunucum:
    build:
      context: ..
      dockerfile: ./docker-files/Dockerfile
    container_name: static_crossle_site_container
    ports:
      - "8080:80"  # Tarayıcıdan 8080 ile erişirsin, konteyner içinde 80 çalışır
    restart: always